#!/usr/bin/env python3
import sys
import re
import os

if __name__ == "__main__":
    # determine used system files from CMakeLists
    os.chdir(os.path.join(os.path.dirname(sys.argv[0]), ".."))
    with open("CMakeLists.txt") as f:
        sysfiles = re.findall(r'sys_\w+\.c', f.read())

    # enumerate systems from these files
    os.chdir(os.path.join("retrofont", "src"))
    systems = []
    for fn in sysfiles:
        with open(fn) as f:
            systems += re.findall(r'^const\s+RF_System\s+(RF_Sys_\w+)\s*=', f.read(), flags=re.M)

    # generate systems.c
    with open("systems.c", "w") as out:
        out.write(f'// This file has been auto-generated by {os.path.basename(sys.argv[0])}. DO NOT EDIT BY HAND!\n\n')
        out.write('#include "retrofont.h"\n\n')
        for sys in systems:
            out.write(f'extern const RF_System {sys};\n')
        out.write('\nconst RF_System* const RF_SystemList[] = {\n')
        for sys in systems:
            out.write(f'    &{sys},\n')
        out.write('    NULL\n};\n')
